/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Mar 17 23:17:10 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CommandLine_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.CommandLine"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\dyw96\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "E:\\EECS-4313\\A2\\commons-cli"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\dyw96"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "dyw96"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CommandLine_ESTest_scaffolding.class.getClassLoader() ,
      "net.bytebuddy.description.modifier.SyntheticState",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.description.TypeVariableSource$AbstractBase",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "org.apache.commons.lang3.StringUtils",
      "net.bytebuddy.utility.MethodComparator",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.bytebuddy.description.type.TypeList$Generic",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.utility.Invoker",
      "net.bytebuddy.description.annotation.AnnotationList",
      "net.bytebuddy.description.ModifierReviewable$ForMethodDescription",
      "net.bytebuddy.description.method.MethodList",
      "net.bytebuddy.dynamic.DynamicType$Builder",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "org.apache.commons.text.matcher.AbstractStringMatcher",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.matcher.FilterableList$Empty",
      "net.bytebuddy.implementation.Implementation$Target",
      "org.apache.commons.text.TextStringBuilder",
      "net.bytebuddy.description.modifier.Visibility",
      "net.bytebuddy.description.modifier.EnumerationState",
      "net.bytebuddy.description.type.RecordComponentList$ForLoadedRecordComponents",
      "net.bytebuddy.dynamic.ClassFileLocator",
      "org.apache.commons.text.similarity.EditDistance",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.description.modifier.ModifierContributor$ForField",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "org.apache.commons.cli.Option$1",
      "net.bytebuddy.description.ModifierReviewable$ForFieldDescription",
      "net.bytebuddy.description.field.FieldList",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.apache.commons.text.similarity.SimilarityScore",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "net.bytebuddy.description.modifier.ModifierContributor$ForType",
      "org.apache.commons.cli.Util",
      "net.bytebuddy.description.type.RecordComponentList$Empty",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Defaults",
      "org.apache.commons.text.Builder",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.jar.asm.RecordComponentWriter",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharMatcher",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.description.type.PackageDescription",
      "net.bytebuddy.implementation.bytecode.StackManipulation",
      "net.bytebuddy.build.Plugin",
      "org.apache.commons.cli.Option",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharArrayMatcher",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.description.method.MethodDescription$InDefinedShape",
      "net.bytebuddy.description.TypeVariableSource$Visitor",
      "net.bytebuddy.description.type.TypeDescription$Generic$Visitor",
      "org.apache.commons.text.similarity.SimilarityInput",
      "net.bytebuddy.jar.asm.MethodWriter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForStaticTypeHash",
      "org.apache.commons.cli.CommandLine$Builder",
      "net.bytebuddy.description.modifier.Ownership",
      "org.apache.commons.cli.AlreadySelectedException",
      "net.bytebuddy.build.Plugin$Factory",
      "net.bytebuddy.description.type.TypeDescription$LazyProxy",
      "org.apache.commons.cli.OptionGroup",
      "net.bytebuddy.matcher.FilterableList",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "net.bytebuddy.jar.asm.MethodTooLargeException",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "net.bytebuddy.description.type.TypeDescription$AbstractBase",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "org.apache.commons.text.matcher.StringMatcherFactory",
      "net.bytebuddy.description.ByteCodeElement$TypeDependant",
      "org.apache.commons.cli.Converter",
      "net.bytebuddy.description.method.MethodDescription",
      "net.bytebuddy.jar.asm.FieldWriter",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "net.bytebuddy.description.type.TypeList",
      "net.bytebuddy.implementation.attribute.AnnotationValueFilter",
      "org.apache.commons.cli.DeprecatedAttributes",
      "net.bytebuddy.description.ModifierReviewable$ForParameterDescription",
      "net.bytebuddy.description.type.TypeList$Generic$ForLoadedTypes",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Proxied",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider",
      "net.bytebuddy.description.TypeVariableSource",
      "net.bytebuddy.description.type.TypeDescription$Generic",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.description.modifier.ModifierContributor",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "net.bytebuddy.jar.asm.ClassTooLargeException",
      "net.bytebuddy.jar.asm.Frame",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "net.bytebuddy.jar.asm.ModuleVisitor",
      "org.apache.commons.cli.ParseException",
      "net.bytebuddy.description.type.TypeDefinition",
      "net.bytebuddy.description.ModifierReviewable$AbstractBase",
      "net.bytebuddy.description.type.TypeDescription",
      "org.apache.commons.io.file.PathFilter",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.implementation.bytecode.ByteCodeAppender",
      "org.apache.commons.text.similarity.HammingDistance",
      "net.bytebuddy.ClassFileVersion",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderReader",
      "net.bytebuddy.description.type.TypeList$Empty",
      "net.bytebuddy.implementation.bytecode.StackSize",
      "org.apache.commons.cli.DeprecatedAttributes$Builder",
      "net.bytebuddy.description.type.RecordComponentList$AbstractBase",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharSetMatcher",
      "net.bytebuddy.description.ByteCodeElement",
      "org.apache.commons.text.matcher.AbstractStringMatcher$NoneMatcher",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType$Dispatcher",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderWriter",
      "net.bytebuddy.description.type.RecordComponentList",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.jar.asm.RecordComponentVisitor",
      "net.bytebuddy.jar.asm.FieldVisitor",
      "net.bytebuddy.description.type.TypeDefinition$Sort",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.CommandLine$1",
      "net.bytebuddy.description.type.TypeList$AbstractBase",
      "org.apache.commons.cli.CommandLine",
      "net.bytebuddy.description.modifier.ModifierContributor$ForMethod",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.implementation.EqualsMethod",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "net.bytebuddy.description.modifier.ModifierContributor$ForParameter",
      "net.bytebuddy.ClassFileVersion$VersionLocator",
      "net.bytebuddy.description.type.TypeList$ForLoadedTypes",
      "net.bytebuddy.jar.asm.ModuleWriter",
      "org.apache.commons.text.StringTokenizer",
      "org.apache.commons.cli.Option$Builder",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.description.modifier.TypeManifestation",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType",
      "org.apache.commons.text.matcher.StringMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$TrimMatcher",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForDynamicTypeHash",
      "net.bytebuddy.matcher.ElementMatcher",
      "net.bytebuddy.description.DeclaredByType$WithMandatoryDeclaration",
      "net.bytebuddy.description.NamedElement$WithGenericName",
      "net.bytebuddy.implementation.HashCodeMethod",
      "net.bytebuddy.matcher.FilterableList$AbstractBase",
      "net.bytebuddy.jar.asm.CurrentFrame",
      "net.bytebuddy.utility.GraalImageCode",
      "net.bytebuddy.description.NamedElement",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.description.type.TypeList$Generic$AbstractBase"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.function.Supplier", false, CommandLine_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CommandLine_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.CommandLine",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.cli.Util",
      "org.apache.commons.cli.Option",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.cli.OptionGroup",
      "org.apache.commons.text.TextStringBuilder",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.cli.DeprecatedAttributes$Builder",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.cli.AlreadySelectedException",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderReader"
    );
  }
}
