/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 17 23:32:38 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLTimeoutException;
import org.apache.commons.cli.ParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseException_ESTest extends ParseException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SQLTimeoutException sQLTimeoutException0 = new SQLTimeoutException();
      ParseException parseException0 = new ParseException(sQLTimeoutException0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UnsupportedOperationException unsupportedOperationException0 = new UnsupportedOperationException("HJ{}kW,-8Brp");
      try { 
        ParseException.wrap(unsupportedOperationException0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseException parseException0 = new ParseException("HJ{}kW,-8Brp");
      ParseException parseException1 = ParseException.wrap(parseException0);
      assertSame(parseException1, parseException0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SQLFeatureNotSupportedException sQLFeatureNotSupportedException0 = new SQLFeatureNotSupportedException();
      ParseException parseException0 = ParseException.wrap(sQLFeatureNotSupportedException0);
      assertNotNull(parseException0);
  }
}
