/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Mar 17 23:18:47 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class PosixParser_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.PosixParser"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\dyw96\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "E:\\EECS-4313\\A2\\commons-cli"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\dyw96"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "dyw96"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PosixParser_ESTest_scaffolding.class.getClassLoader() ,
      "net.bytebuddy.dynamic.DynamicType",
      "net.bytebuddy.dynamic.DynamicType$Unloaded",
      "org.apache.commons.cli.DefaultParser$NonOptionAction",
      "net.bytebuddy.description.TypeVariableSource$AbstractBase",
      "org.apache.commons.lang3.StringUtils",
      "net.bytebuddy.description.type.TypeList$Generic",
      "org.apache.commons.cli.AmbiguousOptionException",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.description.annotation.AnnotationList",
      "net.bytebuddy.description.method.MethodList",
      "net.bytebuddy.description.type.RecordComponentDescription$Token",
      "net.bytebuddy.dynamic.DynamicType$Builder$RecordComponentDefinition$Optional",
      "org.apache.commons.cli.UnrecognizedOptionException",
      "org.apache.commons.text.matcher.AbstractStringMatcher",
      "net.bytebuddy.dynamic.scaffold.TypeInitializer",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ParameterDefinition$Simple",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ImplementationDefinition",
      "org.apache.commons.text.similarity.EditDistance",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "net.bytebuddy.description.modifier.ModifierContributor$ForField",
      "net.bytebuddy.description.ModifierReviewable$ForFieldDescription",
      "net.bytebuddy.description.method.MethodDescription$SignatureToken",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver",
      "org.apache.commons.text.similarity.SimilarityScore",
      "net.bytebuddy.implementation.bytecode.ByteCodeAppender$Size",
      "net.bytebuddy.dynamic.DynamicType$Builder$FieldDefinition$Valuable",
      "net.bytebuddy.utility.visitor.ContextClassVisitor",
      "net.bytebuddy.dynamic.DynamicType$Builder$TypeVariableDefinition",
      "net.bytebuddy.description.modifier.MethodManifestation",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.description.field.FieldDescription",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharMatcher",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "net.bytebuddy.description.method.ParameterList",
      "org.apache.commons.cli.PosixParser",
      "net.bytebuddy.description.modifier.FieldPersistence",
      "org.apache.commons.cli.Option",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharArrayMatcher",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.description.method.MethodDescription$InDefinedShape",
      "net.bytebuddy.jar.asm.TypePath",
      "net.bytebuddy.description.type.TypeDescription$Generic$Visitor",
      "net.bytebuddy.dynamic.DynamicType$Builder$FieldDefinition",
      "net.bytebuddy.implementation.attribute.RecordComponentAttributeAppender",
      "org.apache.commons.text.similarity.SimilarityInput",
      "net.bytebuddy.jar.asm.MethodWriter",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$TypeVariableDefinition$Annotatable",
      "net.bytebuddy.implementation.LoadedTypeInitializer",
      "net.bytebuddy.jar.asm.Handle",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.lang3.function.FailableFunction",
      "net.bytebuddy.description.modifier.Ownership",
      "net.bytebuddy.jar.asm.Context",
      "net.bytebuddy.jar.asm.MethodTooLargeException",
      "net.bytebuddy.description.ByteCodeElement$Token$TokenList",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType",
      "org.apache.commons.cli.MissingArgumentException",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.lang3.mutable.MutableInt",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ParameterDefinition$Annotatable",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "org.apache.commons.cli.DefaultParser",
      "org.apache.commons.text.matcher.StringMatcherFactory",
      "org.apache.commons.cli.Converter",
      "net.bytebuddy.pool.TypePool",
      "net.bytebuddy.description.method.MethodDescription",
      "net.bytebuddy.implementation.attribute.TypeAttributeAppender",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "net.bytebuddy.description.type.TypeList",
      "net.bytebuddy.implementation.attribute.AnnotationValueFilter",
      "org.apache.commons.cli.DeprecatedAttributes",
      "net.bytebuddy.description.method.MethodDescription$TypeToken",
      "net.bytebuddy.description.type.TypeList$Generic$ForLoadedTypes",
      "net.bytebuddy.description.annotation.AnnotationValue$Loaded",
      "net.bytebuddy.implementation.attribute.FieldAttributeAppender",
      "net.bytebuddy.description.modifier.ModifierContributor",
      "net.bytebuddy.description.type.TypeDefinition$Sort$AnnotatedType",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "net.bytebuddy.description.annotation.AnnotationDescription$Loadable",
      "net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record",
      "net.bytebuddy.jar.asm.ClassTooLargeException",
      "net.bytebuddy.description.modifier.FieldManifestation",
      "net.bytebuddy.implementation.MethodAccessorFactory",
      "net.bytebuddy.jar.asm.ModuleVisitor",
      "net.bytebuddy.description.annotation.AnnotationValue$State",
      "net.bytebuddy.description.type.TypeDescription$Generic$LazyProxy",
      "net.bytebuddy.description.ModifierReviewable$AbstractBase",
      "net.bytebuddy.description.type.TypeDescription",
      "net.bytebuddy.implementation.attribute.AnnotationValueFilter$Factory",
      "net.bytebuddy.dynamic.DynamicType$Builder$FieldDefinition$Optional$Valuable",
      "net.bytebuddy.jar.asm.ClassReader",
      "net.bytebuddy.implementation.bytecode.ByteCodeAppender",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ParameterDefinition$Simple$Annotatable",
      "org.apache.commons.text.similarity.HammingDistance",
      "net.bytebuddy.implementation.bytecode.StackSize",
      "org.apache.commons.cli.Options",
      "org.apache.commons.cli.DeprecatedAttributes$Builder",
      "org.apache.commons.lang3.ArrayUtils",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharSetMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$NoneMatcher",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "net.bytebuddy.description.type.RecordComponentDescription$InDefinedShape",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderWriter",
      "net.bytebuddy.description.field.FieldDescription$SignatureToken",
      "net.bytebuddy.description.annotation.AnnotationValue$Sort",
      "net.bytebuddy.description.type.RecordComponentList",
      "net.bytebuddy.jar.asm.RecordComponentVisitor",
      "net.bytebuddy.description.modifier.ParameterManifestation",
      "net.bytebuddy.description.type.TypeList$AbstractBase",
      "org.apache.commons.cli.CommandLine",
      "net.bytebuddy.description.modifier.ModifierContributor$ForMethod",
      "net.bytebuddy.matcher.LatentMatcher",
      "net.bytebuddy.implementation.Implementation$Context",
      "net.bytebuddy.description.modifier.ModifierContributor$ForParameter",
      "net.bytebuddy.jar.asm.ModuleWriter",
      "net.bytebuddy.dynamic.TypeResolutionStrategy",
      "org.apache.commons.cli.CommandLineParser",
      "org.apache.commons.text.StringTokenizer",
      "net.bytebuddy.implementation.auxiliary.AuxiliaryType",
      "org.apache.commons.cli.Option$Builder",
      "net.bytebuddy.description.modifier.TypeManifestation",
      "net.bytebuddy.dynamic.loading.ClassLoadingStrategy",
      "net.bytebuddy.description.modifier.MethodStrictness",
      "net.bytebuddy.implementation.attribute.RecordComponentAttributeAppender$Factory",
      "org.apache.commons.text.matcher.AbstractStringMatcher$TrimMatcher",
      "net.bytebuddy.dynamic.TypeResolutionStrategy$Resolved",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForDynamicTypeHash",
      "net.bytebuddy.matcher.ElementMatcher",
      "net.bytebuddy.description.NamedElement$WithGenericName",
      "net.bytebuddy.implementation.HashCodeMethod",
      "net.bytebuddy.pool.TypePool$Resolution",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.description.type.TypeList$Generic$AbstractBase",
      "net.bytebuddy.description.modifier.SyntheticState",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "org.apache.commons.cli.DefaultParser$Builder",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.utility.MethodComparator",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.bytebuddy.dynamic.DynamicType$Builder$InnerTypeDefinition$ForType",
      "net.bytebuddy.dynamic.DynamicType$Builder$InnerTypeDefinition",
      "net.bytebuddy.dynamic.ClassFileLocator$Resolution",
      "net.bytebuddy.utility.Invoker",
      "net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$Sort",
      "net.bytebuddy.description.type.TypeVariableToken",
      "net.bytebuddy.description.ModifierReviewable$ForMethodDescription",
      "net.bytebuddy.description.annotation.AnnotationValue",
      "net.bytebuddy.dynamic.DynamicType$Builder",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.implementation.Implementation$Context$FrameGeneration",
      "net.bytebuddy.matcher.FilterableList$Empty",
      "net.bytebuddy.description.field.FieldDescription$InDefinedShape",
      "net.bytebuddy.implementation.Implementation$Target",
      "org.apache.commons.text.TextStringBuilder",
      "net.bytebuddy.description.modifier.Visibility",
      "net.bytebuddy.description.modifier.EnumerationState",
      "net.bytebuddy.description.method.MethodDescription$Token",
      "org.apache.commons.cli.Parser",
      "net.bytebuddy.description.type.RecordComponentList$ForLoadedRecordComponents",
      "net.bytebuddy.dynamic.DynamicType$Builder$RecordComponentDefinition",
      "net.bytebuddy.dynamic.ClassFileLocator",
      "net.bytebuddy.description.field.FieldDescription$Token",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "net.bytebuddy.description.field.FieldList",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.lang3.mutable.Mutable",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "net.bytebuddy.description.modifier.ModifierContributor$ForType",
      "org.apache.commons.cli.Util",
      "net.bytebuddy.description.type.RecordComponentList$Empty",
      "net.bytebuddy.description.modifier.SynchronizationState",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ParameterDefinition",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Defaults",
      "org.apache.commons.text.Builder",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.bytebuddy.dynamic.Transformer",
      "net.bytebuddy.jar.asm.RecordComponentWriter",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.implementation.bytecode.StackManipulation$Size",
      "net.bytebuddy.description.type.PackageDescription",
      "net.bytebuddy.implementation.bytecode.StackManipulation",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ImplementationDefinition$Optional",
      "net.bytebuddy.build.Plugin",
      "net.bytebuddy.description.annotation.AnnotationDescription",
      "net.bytebuddy.description.TypeVariableSource$Visitor",
      "org.apache.commons.cli.MissingOptionException",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider$ForStaticTypeHash",
      "net.bytebuddy.implementation.MethodAccessorFactory$AccessType",
      "org.apache.commons.cli.AlreadySelectedException",
      "net.bytebuddy.build.Plugin$Factory",
      "net.bytebuddy.description.type.TypeDescription$LazyProxy",
      "net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$TypeVariableDefinition",
      "org.apache.commons.cli.OptionGroup",
      "net.bytebuddy.jar.asm.Label",
      "net.bytebuddy.matcher.FilterableList",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "net.bytebuddy.description.modifier.ProvisioningState",
      "net.bytebuddy.description.type.TypeDescription$AbstractBase",
      "net.bytebuddy.description.type.PackageDescription$Simple",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ExceptionDefinition",
      "net.bytebuddy.jar.asm.Attribute$Set",
      "net.bytebuddy.description.ByteCodeElement$TypeDependant",
      "net.bytebuddy.jar.asm.FieldWriter",
      "net.bytebuddy.description.ModifierReviewable$ForParameterDescription",
      "net.bytebuddy.implementation.Implementation$Context$FrameGeneration$3",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Proxied",
      "net.bytebuddy.implementation.HashCodeMethod$OffsetProvider",
      "net.bytebuddy.description.TypeVariableSource",
      "net.bytebuddy.description.type.TypeDescription$Generic",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.bytebuddy.dynamic.DynamicType$Loaded",
      "net.bytebuddy.jar.asm.Frame",
      "net.bytebuddy.implementation.Implementation$Context$FrameGeneration$2",
      "net.bytebuddy.implementation.Implementation$Context$FrameGeneration$1",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "net.bytebuddy.description.type.RecordComponentDescription",
      "org.apache.commons.cli.ParseException",
      "net.bytebuddy.description.type.TypeDefinition",
      "org.apache.commons.io.file.PathFilter",
      "net.bytebuddy.description.ByteCodeElement$Token",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.ClassFileVersion",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderReader",
      "net.bytebuddy.description.type.TypeList$Empty",
      "net.bytebuddy.description.type.RecordComponentList$AbstractBase",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.dynamic.DynamicType$Builder$FieldDefinition$Optional",
      "net.bytebuddy.description.ByteCodeElement",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ReceiverTypeDefinition",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType$Dispatcher",
      "net.bytebuddy.implementation.Implementation$SpecialMethodInvocation",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.jar.asm.FieldVisitor",
      "net.bytebuddy.description.type.TypeDefinition$Sort",
      "org.apache.commons.cli.OptionValidator",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.implementation.EqualsMethod",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "net.bytebuddy.ClassFileVersion$VersionLocator",
      "net.bytebuddy.description.type.TypeList$ForLoadedTypes",
      "net.bytebuddy.asm.AsmVisitorWrapper",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.jar.asm.ConstantDynamic",
      "net.bytebuddy.description.type.TypeDescription$ForLoadedType",
      "net.bytebuddy.description.type.PackageDescription$AbstractBase",
      "org.apache.commons.text.matcher.StringMatcher",
      "net.bytebuddy.description.DeclaredByType$WithMandatoryDeclaration",
      "net.bytebuddy.implementation.attribute.FieldAttributeAppender$Factory",
      "net.bytebuddy.matcher.FilterableList$AbstractBase",
      "net.bytebuddy.jar.asm.CurrentFrame",
      "net.bytebuddy.utility.GraalImageCode",
      "net.bytebuddy.dynamic.DynamicType$Builder$MethodDefinition$ParameterDefinition$Initial",
      "net.bytebuddy.description.NamedElement"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PosixParser_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Parser",
      "org.apache.commons.cli.PosixParser",
      "org.apache.commons.cli.Util",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.Options",
      "org.apache.commons.cli.CommandLine",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.cli.Option",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.OptionGroup",
      "org.apache.commons.text.TextStringBuilder",
      "org.apache.commons.text.matcher.AbstractStringMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$NoneMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharSetMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$TrimMatcher",
      "org.apache.commons.text.matcher.StringMatcherFactory",
      "org.apache.commons.text.StringTokenizer",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.cli.MissingOptionException",
      "org.apache.commons.cli.UnrecognizedOptionException",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.cli.DefaultParser",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.cli.MissingArgumentException",
      "org.apache.commons.cli.DeprecatedAttributes$Builder",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.cli.AmbiguousOptionException"
    );
  }
}
