/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Mar 17 23:35:08 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypeHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.TypeHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\dyw96\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "E:\\EECS-4313\\A2\\commons-cli"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\dyw96"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "dyw96"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypeHandler_ESTest_scaffolding.class.getClassLoader() ,
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$SingletonEnumeration",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.utility.MethodComparator",
      "org.apache.commons.cli.Converter",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.jar.asm.FieldWriter",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader",
      "net.bytebuddy.dynamic.loading.PackageDefinitionStrategy",
      "net.bytebuddy.utility.Invoker",
      "net.bytebuddy.description.annotation.AnnotationList",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$EmptyEnumeration",
      "org.apache.commons.text.lookup.XmlDecoderStringLookup",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Proxied",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.jar.asm.ClassTooLargeException",
      "net.bytebuddy.jar.asm.Frame",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.jar.asm.ModuleVisitor",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "net.bytebuddy.dynamic.loading.InjectionClassLoader",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ChildFirst",
      "org.apache.commons.cli.ParseException",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.description.NamedElement$WithOptionalName",
      "net.bytebuddy.utility.JavaModule",
      "net.bytebuddy.ClassFileVersion",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "net.bytebuddy.dynamic.loading.ClassFilePostProcessor",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.jar.asm.RecordComponentWriter",
      "net.bytebuddy.utility.JavaModule$Resolver",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.jar.asm.RecordComponentVisitor",
      "net.bytebuddy.jar.asm.FieldVisitor",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.ClassFileVersion$VersionLocator",
      "net.bytebuddy.jar.asm.ModuleWriter",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.jar.asm.MethodWriter",
      "org.apache.commons.cli.TypeHandler",
      "org.apache.commons.text.lookup.StringLookup",
      "org.apache.commons.lang3.function.FailableSupplier",
      "net.bytebuddy.jar.asm.CurrentFrame",
      "net.bytebuddy.matcher.FilterableList",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "net.bytebuddy.utility.GraalImageCode",
      "net.bytebuddy.description.NamedElement",
      "net.bytebuddy.jar.asm.MethodTooLargeException",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypeHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "net.bytebuddy.dynamic.loading.InjectionClassLoader",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$CreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader$Resolver$NoOp",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "net.bytebuddy.ClassFileVersion",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "net.bytebuddy.utility.GraalImageCode",
      "net.bytebuddy.utility.MethodComparator",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "net.bytebuddy.jar.asm.MethodWriter",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.utility.JavaModule",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.lang3.function.FailableSupplier",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.text.lookup.XmlDecoderStringLookup",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.hsqldb.jdbc.JDBCDriver",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$SingletonEnumeration",
      "org.apache.commons.text.StrLookup$SystemPropertiesStrLookup",
      "org.apache.commons.text.StrLookup",
      "org.apache.commons.text.StrLookup$MapStrLookup",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.serialization.FullClassNameMatcher",
      "net.bytebuddy.description.modifier.SyntheticState",
      "net.bytebuddy.implementation.auxiliary.AuxiliaryType",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.junitpioneer.jupiter.DisableIfTestFailsExtension",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.FileEqualsFileFilter",
      "org.apache.commons.text.lookup.ResourceBundleStringLookup",
      "org.apache.commons.io.file.Counters$NoopCounter",
      "org.apache.commons.io.filefilter.DirectoryFileFilter",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.junitpioneer.vintage.ExpectedExceptionExtension",
      "net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$DelegationProcessor",
      "net.bytebuddy.asm.Advice$AssignReturned$DefaultValueSkip",
      "org.apache.commons.text.lookup.UrlEncoderStringLookup",
      "org.apache.commons.text.similarity.IntersectionSimilarity$TinyBag",
      "org.junitpioneer.jupiter.AbstractEntryBasedExtension",
      "org.junitpioneer.jupiter.EnvironmentVariableExtension",
      "org.junitpioneer.jupiter.cartesian.CartesianEnumArgumentsProvider",
      "net.bytebuddy.build.Plugin$ForElementMatcher",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.filefilter.WildcardFilter"
    );
  }
}
