/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Mar 17 23:34:18 GMT 2026
 */

package org.apache.commons.cli.help;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class HelpAppendable_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.help.HelpAppendable"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\dyw96\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "E:\\EECS-4313\\A2\\commons-cli"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\dyw96"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "dyw96"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(HelpAppendable_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$3",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$2",
      "net.bytebuddy.description.ModifierReviewable$OfAbstraction",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$4",
      "org.apache.commons.lang3.StringUtils",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper$1",
      "net.bytebuddy.description.ModifierReviewable$OfEnumeration",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.help.TextStyle$1",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender",
      "org.apache.commons.cli.DeprecatedAttributes",
      "net.bytebuddy.description.TypeVariableSource",
      "net.bytebuddy.implementation.attribute.MethodAttributeAppender$Factory",
      "net.bytebuddy.description.ModifierReviewable$ForTypeDefinition",
      "net.bytebuddy.description.type.TypeDefinition",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin",
      "org.apache.commons.text.similarity.SimilarityScore",
      "net.bytebuddy.description.type.TypeDescription",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "org.apache.commons.cli.help.Util",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.help.FilterHelpAppendable",
      "net.bytebuddy.description.ModifierReviewable",
      "net.bytebuddy.description.ModifierReviewable$OfByteCodeElement",
      "net.bytebuddy.implementation.Implementation",
      "net.bytebuddy.description.ByteCodeElement",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "net.bytebuddy.dynamic.scaffold.InstrumentedType$Prepareable",
      "org.apache.commons.cli.help.TextHelpAppendable",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance",
      "org.apache.commons.cli.help.TextStyle",
      "net.bytebuddy.description.DeclaredByType",
      "net.bytebuddy.build.Plugin",
      "org.apache.commons.cli.help.HelpAppendable",
      "org.apache.commons.cli.Option",
      "net.bytebuddy.description.annotation.AnnotationSource",
      "net.bytebuddy.implementation.EqualsMethod",
      "net.bytebuddy.description.NamedElement$WithRuntimeName",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.help.TableDefinition",
      "net.bytebuddy.description.NamedElement$WithDescriptor",
      "net.bytebuddy.matcher.ElementMatcher",
      "net.bytebuddy.build.Plugin$Factory",
      "org.apache.commons.cli.help.TableDefinition$1",
      "net.bytebuddy.implementation.HashCodeMethod",
      "net.bytebuddy.description.NamedElement"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.Comparator", false, HelpAppendable_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(HelpAppendable_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.help.FilterHelpAppendable",
      "org.apache.commons.cli.help.TextHelpAppendable",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.help.TextStyle",
      "org.apache.commons.cli.help.Util",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.cli.help.TextStyle$1",
      "org.apache.commons.cli.help.TableDefinition$1",
      "org.apache.commons.cli.Option",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.cli.help.TextStyle$Alignment"
    );
  }
}
