/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 17 23:34:18 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.StringWriter;
import java.nio.CharBuffer;
import java.nio.ReadOnlyBufferException;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Stack;
import java.util.TreeSet;
import java.util.UnknownFormatConversionException;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpAppendable_ESTest extends HelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      textHelpAppendable0.appendTitle(charBuffer0);
      assertFalse(charBuffer0.hasRemaining());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      Vector<String> vector1 = new Vector<String>();
      ArrayList<List<String>> arrayList0 = new ArrayList<List<String>>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>(arrayList0);
      TableDefinition tableDefinition0 = TableDefinition.from("", vector0, vector1, hashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      textHelpAppendable0.appendHeader(2973, "");
      assertEquals(1, textHelpAppendable0.getLeftPad());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[0];
      textHelpAppendable0.appendFormat(" does not define ", objectArray0);
      assertEquals(74, textHelpAppendable0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      textHelpAppendable0.appendParagraph(charBuffer0);
      assertEquals(0, charBuffer0.length());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      ArrayDeque<CharSequence> arrayDeque0 = new ArrayDeque<CharSequence>();
      textHelpAppendable0.appendList(true, arrayDeque0);
      assertTrue(arrayDeque0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[5];
      textHelpAppendable0.appendParagraphFormat("", objectArray0);
      assertEquals(74, textHelpAppendable0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = stringWriter0.append('R');
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      textHelpAppendable0.setLeftPad((-1097462182));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(stringBuffer0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>(comparator0);
      TableDefinition tableDefinition0 = TableDefinition.from("Expected an interface instead of ", stack0, (List<String>) null, treeSet0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayDeque<Option> arrayDeque0 = new ArrayDeque<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayDeque0);
      List<String> list0 = tableDefinition0.headers();
      ArrayDeque<List<String>> arrayDeque1 = new ArrayDeque<List<String>>();
      TableDefinition tableDefinition1 = TableDefinition.from("", vector0, list0, arrayDeque1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("h]b62%", (Object[]) null);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = '%'
         //
         verifyException("java.util.Formatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      Object[] objectArray0 = new Object[9];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("~m1O", objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad((-1514));
      Object[] objectArray0 = new Object[8];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("k(", objectArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setMaxWidth((-1392));
      Object[] objectArray0 = new Object[4];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("AF&t HnrqM(\"", objectArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(74);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader((-2305), charBuffer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[7];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) stringBuffer0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      Object[] objectArray0 = new Object[2];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("8Cv3", objectArray0);
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }
}
