/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 17 23:17:10 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.Month;
import java.time.format.TextStyle;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('-', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      CommandLine commandLine0 = commandLine_Builder1.get();
      assertNotNull(commandLine0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("ooEc", "Classpath resource must not be null or blank");
      optionGroup0.setSelected(option0);
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("true", "initialList");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      boolean boolean0 = commandLine0.hasOption("true");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getArgs();
      String[] stringArray1 = commandLine0.getParsedOptionValues(optionGroup0, stringArray0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStyle[] textStyleArray0 = new TextStyle[7];
      Supplier<TextStyle[]> supplier0 = (Supplier<TextStyle[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(textStyleArray0).when(supplier0).get();
      TextStyle[] textStyleArray1 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<TextStyle[]>) supplier0);
      assertSame(textStyleArray1, textStyleArray0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = new Option[1];
      Option[] optionArray1 = commandLine0.getParsedOptionValues((Option) null, optionArray0);
      assertEquals(1, optionArray1.length);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[0];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues((Option) null, integerArray0);
      assertSame(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("yhbnYR8", true, "[$7PcL");
      Object[] objectArray0 = new Object[0];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues(option0, (Supplier<Object[]>) supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getParsedOptionValues("F", (String[]) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[7];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues("", integerArray0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer[] integerArray0 = new Integer[6];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues("", (Supplier<Integer[]>) supplier0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer[] integerArray0 = new Integer[0];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues("org.apache.commons.cli.CommandLine@0000000002", (Supplier<Integer[]>) supplier0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[1];
      Object[] objectArray1 = commandLine0.getParsedOptionValues('D', objectArray0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<LinkedList<Integer>[]> supplier0 = (Supplier<LinkedList<Integer>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      LinkedList<Integer>[] linkedListArray0 = commandLine0.getParsedOptionValues('|', supplier0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = new Option[6];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues('Z', (Supplier<Option[]>) supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue(option0, (Supplier<Object>) supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue((Option) null, (Object) commandLine_Builder0);
      assertSame(object0, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Class<String>> supplier0 = (Supplier<Class<String>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Class<String> class0 = commandLine0.getParsedOptionValue("suffixes", supplier0);
      assertNull(class0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue((String) null, (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue('B', (Supplier<Object>) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue('Y', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, "[$7PcL", true, "=fL_%N5QBTJG/< t<7");
      commandLine0.addOption(option0);
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "org.apache.commons.cli.CommandLine$Builder");
      assertEquals("org.apache.commons.cli.CommandLine$Builder", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, true, "args");
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("hN}K7eYv?Nav_{");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("hN}K7eYv?Nav_{", string0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, "org.apache.commons.io.filefilter.MagicNumberFileFilter");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(0);
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("rf", true, (String) null);
      String string0 = commandLine0.getOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      String string0 = commandLine0.getOptionValue(option0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue("[m&{j7GRK6^t `}Kfi ", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getOptionValue("z", (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("K<=Yvh'b:A8\"0[.W", (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("J2", "Z}ZJ");
      assertNotNull(string0);
      assertEquals("Z}ZJ", string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[1];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0, 1);
      String string0 = commandLine0.getOptionValue('9', (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((String) null);
      String string0 = commandLine0.getOptionValue('o', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('m', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('x', "R*");
      assertEquals("R*", string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, "[9EQ_NJ", false, "[9EQ_NJ");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      int int0 = commandLine0.getOptionCount("r-_EIbnkhdhv:P");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addArg("[$7PcL");
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("v!!\"7|Ez");
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains("v!!\"7|Ez"));
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      Option.Builder option_Builder0 = Option.builder();
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue("org.apache.commons.cli.Util", (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("J2", "options", true, "Z^HvN");
      boolean boolean0 = commandLine0.hasOption(option0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("ooEc", "Classpath resource must not be null or blank");
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<String[]>) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStyle[] textStyleArray0 = new TextStyle[0];
      Supplier<TextStyle[]> supplier0 = (Supplier<TextStyle[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(textStyleArray0).when(supplier0).get();
      TextStyle[] textStyleArray1 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<TextStyle[]>) supplier0);
      assertSame(textStyleArray0, textStyleArray1);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, (Supplier<Integer[]>) null);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Class<Object>[]> supplier0 = (Supplier<Class<Object>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Class<Object>[] classArray0 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("args", false, "args");
      Option[] optionArray0 = new Option[2];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertEquals(2, optionArray1.length);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "[]");
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("[]", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("args", "args", false, "args");
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("args");
      optionGroup0.setSelected(option0);
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("args", string0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((Option) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(option0).when(supplier0).get();
      Option option1 = (Option)commandLine0.getParsedOptionValue(option0, (Supplier<Object>) supplier0);
      assertFalse(option1.hasArgs());
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((Option) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null);
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "args");
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("args", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = commandLine0.getParsedOptionValue('1', (Supplier<Option>) option_Builder0);
      String[] stringArray0 = commandLine0.getParsedOptionValues(option0, (String[]) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("z", (Supplier<Object[]>) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("0_");
      Option option0 = commandLine0.getParsedOptionValue("z", (Supplier<Option>) option_Builder0);
      assertEquals((-1), Option.UNINITIALIZED);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount((Option) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("beoFg2Ln6C3o$");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Class<Object>[] classArray0 = commandLine0.getParsedOptionValues("yS");
      assertNull(classArray0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      Option option1 = commandLine0.getParsedOptionValue(option0);
      assertNull(option1);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "args");
      String string0 = commandLine0.getOptionValue("z", (Supplier<String>) textStringBuilder0);
      assertEquals("args", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption("?J>o|3=6-G=p4/uAo");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      String string0 = commandLine0.getOptionValue(option0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getParsedOptionValue((Option) null, (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[0];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues((String) null, integerArray0);
      assertEquals(0, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      option_Builder1.longOpt("");
      Option option0 = option_Builder1.get();
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      option_Builder1.longOpt("");
      Option option0 = option_Builder1.get();
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getParsedOptionValues((OptionGroup) null);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStyle[] textStyleArray0 = commandLine0.getParsedOptionValues(option0);
      assertNull(textStyleArray0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Integer integer0 = commandLine0.getParsedOptionValue(optionGroup0, (Integer) (-1));
      assertEquals((-1), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue((OptionGroup) null, (Supplier<Integer>) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      commandLine_Builder0.addOption(option0);
      String string0 = commandLine0.getParsedOptionValue("");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = commandLine0.getParsedOptionValue(optionGroup0);
      assertNull(option0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues('P');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getOptions();
      Object[] objectArray0 = commandLine0.getParsedOptionValues('`', (Object[]) optionArray0);
      assertSame(optionArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      List<String> list0 = commandLine0.getArgList();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("vyU", "r-_EIbnkhdhv:P", true, "vyU");
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue(option0, "vyU");
      assertEquals("vyU", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption('[');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getOptionObject('[');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = new String[1];
      String[] stringArray1 = commandLine0.getParsedOptionValues(optionGroup0, stringArray0);
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Properties properties0 = commandLine0.getOptionProperties("args");
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = new String[0];
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      String[] stringArray1 = commandLine0.getParsedOptionValues('P', (Supplier<String[]>) supplier0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject("WG'?!K?'c#iHyS");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues('[');
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues("ooEc");
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount('B');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Option> linkedList0 = new LinkedList<Option>();
      LinkedList<Option> linkedList1 = commandLine0.getParsedOptionValue('.', linkedList0);
      assertSame(linkedList0, linkedList1);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('|', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue('O', (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount("S`");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue("", (Object) "");
      assertEquals("", object0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = commandLine0.getParsedOptionValue('4');
      assertNull(option0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Month[] monthArray0 = commandLine0.getParsedOptionValues('n', (Month[]) null);
      assertNull(monthArray0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('X');
      assertNull(string0);
  }
}
